name: Run CI on Pull Request
on: pull_request
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: git fetch --no-tags --prune --depth=5 origin main
      - name: Install packages
        run: npm ci
      - name: Run linter on affected
        run: npm run affected:lint -- --base=origin/main
      - name: Run unit tests on affected
        run: npm run affected:test -- --base=origin/main
      - name: Run build on affected
        run: npm run affected:build -- --base=origin/main
