name: Release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: 'Git fetch for affected commands'
        run: git fetch --no-tags --prune --depth=5 origin main
      - name: NPM install, lint, build and test
        run: |
          npm ci
          npm run affected:lint -- --base=origin/main
          npm run affected:build -- --base=origin/main
          npm run affected:test -- --base=origin/main
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npx semantic-release --debug
      - name: Bump package.json version
        run: |
          npm run bump -- "this.version='${{ steps.semantic.outputs.new_release_version }}'"
